ALTER TABLE Ventas
ADD COLUMN fechaPago DATETIME NULL,
ADD COLUMN Estatus VARCHAR(2) DEFAULT 'AC',
ADD COLUMN usuario VARCHAR(50),
ADD COLUMN UsuarioCierra VARCHAR(50),
ADD COLUMN FechaCierre DATETIME NULL;
