
CREATE TABLE [dbo].[VentaDetalle](
	[idVenta] [nchar](10) NOT NULL,
	[producto] [nvarchar](15) NOT NULL,
	[cantidad] [smallint] NOT NULL,
	[total] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_VentaDetalle] PRIMARY KEY CLUSTERED 
(
	[idVenta] ASC,
	[producto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

--EN ESTA TABLA VENDRIA EL DETALLE DE LA VENTA CON CADA PRODUCTO QUE SE COMPRO SE UNE A LA  TABLA VENTAS QUE TRAE EL DETALLLE CON IDVENTA


